### ISSUE TITLE
Integrate Record Linked apps

### ISSUE THREAD

**Issue by spatialguerilla** [CenturyGIS/sequelize-auto-fulcrum#3]
@eczajk1 - Record linked apps could be recursively added as models.  Easier said than done, but this would eliminate the need to identify these each time in the future.  This will become especially important as we will be using record linking a lot more in future apps, in some cases with multiple record links in a single app and / or multiple apps daisy chained together...

**Comment by eczajk1** [comment]
You mean like issue a command to generate sequelize models for a given app and have it generate models for the record linked apps at the same time?

I could see how that would be helpful, although a little tricky to configure since we typically want each app's tables in it's own schema.

**Comment by spatialguerilla** [comment]
Correct, especially with the pending Construction app re-design, which will see the app broken out from 2 apps (Construction / Catalog) into about 6 apps all record linked together.  This is going to become the norm more and more going forward.

**Comment by eczajk1** [comment]
fyi, i removed the linked document because this is a public repository

**Comment by eczajk1** [comment]
closing this for now since we don't have a clear way to do this

**Comment by eczajk1** [comment]
I think 8b907654e0e45c70257ad55f19ee227d634c680f relates to this issue. It's not recursively adding models, but simply adding additional models for record linked fields where multiple linked records are allowed.
